modLoader="lowcodefml"
loaderVersion="[1,)"
license="Unlicense"

[[mods]]
modId="scion"
version="1.0"
displayName="Scion"
description="A tree loosely inspired by DnD and Path of Exile"
authors="Pufferfish's Template Generator"